# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TEST.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#import PY_Serial as Ser
import json

layout_x=[335,295,255,215,175,135,90,55,15,0]

Device_Amount_list=[]
Control_Device_list=[]
Device_Type_list=[]
Device_Title_list=[]

# 讀取 JSON 檔案
JSON = open("user_set.json",encoding="utf-8") #as f:
p = json.load(JSON)
list_num=len(p["Device_login"])
print(p)
# 查看整個 JSON 資料解析後的結果
for i in range(list_num):
    Control_Device_list.append(p["Device_login"][i]['Control'])
    Device_Amount_list.append(p["Device_login"][i]['Amount'])
    Device_Type_list.append(p["Device_login"][i]['Type'])
    Device_Title_list.append(p["Device_login"][i]['NAME'])
    


SWITCH_RAM=0
FAB_RAM=0



class Ui_MainWindow(object):
    def test(self,num):
        self.stackedWidget.setCurrentIndex(num)
    def test2(self,num):
        #print(num)
        Ser.control_Relay(num)
    def set_Page_BT(self,BT_NUM):
        self.page_bt[BT_NUM].clicked.connect(lambda:self.test(BT_NUM))
    def set_ON_Control_BT(self,BT_Type,BT_NUM_1,BT_NUM_2):
        self.ON_bt[BT_NUM_1].clicked.connect(lambda:self.test2(BT_Type+"_ON_"+str(BT_NUM_2)))
    def set_STOP_Control_BT(self,BT_Type,BT_NUM_1,BT_NUM_2):
        self.STOP_bt[BT_NUM_1].clicked.connect(lambda:self.test2(BT_Type+"_STOP_"+str(BT_NUM_2)))
    def set_OFF_Control_BT(self,BT_Type,BT_NUM_1,BT_NUM_2):
        self.OFF_bt[BT_NUM_1].clicked.connect(lambda:self.test2(BT_Type+"_OFF_"+str(BT_NUM_2)))
    
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(860, 0, 160, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_bt={}
        self.ON_bt={}
        self.STOP_bt={}
        self.OFF_bt={}
        self.Title_list={}
        #側邊按紐字體設定
        self.BT_font = QtGui.QFont()
        self.BT_font.setFamily("微軟正黑體 Light")
        self.BT_font.setPointSize(30)
        self.BT_font.setWeight(75)
        
        #控制按紐字體設定
        self.Control_font = QtGui.QFont()
        self.Control_font.setFamily("微軟正黑體 Light")
        self.Control_font.setPointSize(30)
        self.Control_font.setWeight(75)
        
        #標題字體設定
        self.Control_Title = QtGui.QFont()
        self.Control_Title.setFamily("微軟正黑體")
        self.Control_Title.setPointSize(20)
        self.Control_Title.setBold(True)
        self.Control_Title.setWeight(75)
        
        
        self.page={}#頁面陣列

        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 240, 751, 331))
        self.stackedWidget.setObjectName("stackedWidget")
        
        
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 601, 81))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 530, 161, 51))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")


        for i in range(len(Control_Device_list)):#透過陣列元素生成頁面切換按鈕
            if(Device_Title_list[i]!=""):
                NAME=Device_Title_list[i].split(",")
            else :
                NAME=""

            NUM_RAM=Device_Amount_list[i]
            self.page_bt[i]=QtWidgets.QPushButton(self.verticalLayoutWidget,objectName="to_Page_"+str(i))
            self.page_bt[i].setFont(self.BT_font)
            self.set_Page_BT(i)
            self.verticalLayout.addWidget(self.page_bt[i])
            
            self.page[i]= QtWidgets.QWidget()
            self.page[i].setObjectName("page_"+str(i))
            
            
            #透過元素生成4個layout
            #生成頁面
            self.lable=QtWidgets.QLabel(self.page[i])
            self.lable.setText(Control_Device_list[i]+"控制")
            self.lable.setGeometry(QtCore.QRect(0, 0, 121, 41))
            self.lable.setFont(self.Control_Title)
           
            self.horizontalLayoutWidget = QtWidgets.QWidget(self.page[i])
            self.horizontalLayoutWidget.setGeometry(QtCore.QRect(layout_x[NUM_RAM-1], 50, (75*Device_Amount_list[i])+1, 30))
            self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
            self.Title_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
            self.Title_Layout.setContentsMargins(0, 0, 0, 0)
            self.Title_Layout.setObjectName("Title_Layout")

            self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page[i])
            self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(layout_x[NUM_RAM-1], 80, (75*Device_Amount_list[i])+1, 80))
            self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
            self.ON_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
            self.ON_Layout.setContentsMargins(0, 0, 0, 0)
            self.ON_Layout.setObjectName("ON_Layout")
            
            self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.page[i])
            self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(layout_x[NUM_RAM-1], 160, (75*Device_Amount_list[i])+1, 80))
            self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
            self.STOP_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
            self.STOP_Layout.setContentsMargins(0, 0, 0, 0)
            self.STOP_Layout.setObjectName("STOP_Layout")
            
            self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.page[i])
            self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(layout_x[NUM_RAM-1], 240, (75*Device_Amount_list[i])+1, 80))
            self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
            self.OFF_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
            self.OFF_Layout.setContentsMargins(0, 0, 0, 0)
            self.OFF_Layout.setObjectName("OFF_Layout")
            self.stackedWidget.addWidget (self.page[i])
            
            if Device_Type_list[i]=="開關":
                global SWITCH_RAM
                
                for j in range(Device_Amount_list[i]):
                    SWITCH_RAM=SWITCH_RAM+1
                    if (NAME==""):
                        #設定編號標題
                        self.Title_list[i]=QtWidgets.QLabel(self.horizontalLayoutWidget)
                        self.Title_list[i].setText(str(j+1)+"號")
                        self.Title_list[i].setAlignment(QtCore.Qt.AlignCenter)
                        self.Title_list[i].setFont(self.Control_Title)
                        self.Title_Layout.addWidget(self.Title_list[i])
                    else :
                        #設定編號標題
                        self.Title_list[i]=QtWidgets.QLabel(self.horizontalLayoutWidget)
                        self.Title_list[i].setText(NAME[j])
                        self.Title_list[i].setAlignment(QtCore.Qt.AlignCenter)
                        self.Title_list[i].setFont(self.Control_Title)
                        self.Title_Layout.addWidget(self.Title_list[i])
                    #設定開關型設備 啟動按紐
                    self.ON_bt[i]=QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
                    self.ON_bt[i].setFont(self.Control_font)
                    self.ON_bt[i].setText("開")
                    self.ON_bt[i].setStyleSheet("background-color : rgba(67, 255,67, 255); ")
                    self.ON_Layout.addWidget(self.ON_bt[i])
                    self.set_ON_Control_BT("SWITCH",i,SWITCH_RAM)
                    #設定開關型設備 關閉按紐
                    self.OFF_bt[i]=QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
                    self.OFF_bt[i].setFont(self.Control_font)
                    self.OFF_bt[i].setText("關")
                    self.OFF_bt[i].setStyleSheet("background-color : rgba(255, 67,67, 255);")
                    self.OFF_Layout.addWidget(self.OFF_bt[i])
                    self.set_OFF_Control_BT("SWITCH",i,SWITCH_RAM)

            elif Device_Type_list[i]=="往復":
                global FAB_RAM
                for j in range(Device_Amount_list[i]):
                    FAB_RAM=FAB_RAM+1
                    if (NAME==""):
                        #設定編號標題
                        self.Title_list[i]=QtWidgets.QLabel(self.horizontalLayoutWidget)
                        self.Title_list[i].setText(str(j+1)+"號")
                        self.Title_list[i].setAlignment(QtCore.Qt.AlignCenter)
                        self.Title_list[i].setFont(self.Control_Title)
                        self.Title_Layout.addWidget(self.Title_list[i])
                    else :
                        #設定編號標題
                        self.Title_list[i]=QtWidgets.QLabel(self.horizontalLayoutWidget)
                        self.Title_list[i].setText(NAME[j])
                        self.Title_list[i].setAlignment(QtCore.Qt.AlignCenter)
                        self.Title_list[i].setFont(self.Control_Title)
                        self.Title_Layout.addWidget(self.Title_list[i])
                    #設定編號標題
                    #self.Title_list[i]=QtWidgets.QLabel(self.horizontalLayoutWidget)
                    #self.Title_list[i].setText(str(j+1)+"號")
                    #self.Title_list[i].setAlignment(QtCore.Qt.AlignCenter)
                    #self.Title_list[i].setFont(self.Control_Title)
                    #self.Title_Layout.addWidget(self.Title_list[i])
                    #設定往復型設備 啟動按紐
                    self.ON_bt[i]=QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
                    self.ON_bt[i].setFont(self.Control_font)
                    self.ON_bt[i].setText("開")
                    self.ON_bt[i].setStyleSheet("background-color : rgba(67, 255,67, 255);")
                    self.ON_Layout.addWidget(self.ON_bt[i])
                    self.set_ON_Control_BT("FAB",i,FAB_RAM)
                    #設定往復型設備 停止按紐
                    self.STOP_bt[i]=QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
                    self.STOP_bt[i].setFont(self.Control_font)
                    self.STOP_bt[i].setText("停")
                    self.STOP_bt[i].setStyleSheet("background-color : rgba(243, 255,67, 255);")
                    self.STOP_Layout.addWidget(self.STOP_bt[i])
                    self.set_STOP_Control_BT("FAB",i,FAB_RAM)
                    #設定往復型設備 關閉按紐
                    self.OFF_bt[i]=QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
                    self.OFF_bt[i].setFont(self.Control_font)
                    self.OFF_bt[i].setText("關")
                    self.OFF_bt[i].setStyleSheet("background-color : rgba(255, 67,67, 255);")
                    self.OFF_Layout.addWidget(self.OFF_bt[i])
                    self.set_OFF_Control_BT("FAB",i,FAB_RAM)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        for j in range(len(Control_Device_list)):
            self.page_bt[j].setText(_translate("MainWindow", Control_Device_list[j]))
        
        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "設備"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "溫度"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "濕度"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "光照度"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "時間"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
